```yaml id="m3w8pk"
---
- name: Build and Push Docker Image
  hosts: docker
  become: true

  vars:
    image_name: "shahid848/maven-web-app"
    image_tag: "latest"

  tasks:

    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: /home/ansadmin/Dockerfile

    - name: Copy Build Artifact
      copy:
        src: target/
        dest: /home/ansadmin/target/

    - name: Build Docker Image
      command: docker build -t {{ image_name }}:{{ image_tag }} /home/ansadmin

    - name: Push Docker Image
      command: docker push {{ image_name }}:{{ image_tag }}

- name: Deploy Application to EKS
  hosts: eks
  become: true

  tasks:

    - name: Copy Kubernetes Deployment File
      copy:
        src: k8s-deploy.yml
        dest: /home/ansadmin/k8s-deploy.yml

    - name: Deploy to Kubernetes
      command: kubectl apply -f /home/ansadmin/k8s-deploy.yml

    - name: Verify Deployment
      command: kubectl get pods
      register: pod_status

    - name: Display Pod Status
      debug:
        var: pod_status.stdout_lines
```
